/*
 * Copyright 2018, Cypress Semiconductor Corporation or a subsidiary of 
 * Cypress Semiconductor Corporation. All Rights Reserved.
 * 
 * This software, associated documentation and materials ("Software"),
 * is owned by Cypress Semiconductor Corporation
 * or one of its subsidiaries ("Cypress") and is protected by and subject to
 * worldwide patent protection (United States and foreign),
 * United States copyright laws and international treaty provisions.
 * Therefore, you may use this Software only as provided in the license
 * agreement accompanying the software package from which you
 * obtained this Software ("EULA").
 * If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 * non-transferable license to copy, modify, and compile the Software
 * source code solely for use in connection with Cypress's
 * integrated circuit products. Any reproduction, modification, translation,
 * compilation, or representation of this Software except as specified
 * above is prohibited without the express written permission of Cypress.
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
 * reserves the right to make changes to the Software without notice. Cypress
 * does not assume any liability arising out of the application or use of the
 * Software or any product or circuit described in the Software. Cypress does
 * not authorize its products for use in any products where a malfunction or
 * failure of the Cypress product may reasonably be expected to result in
 * significant property damage, injury or death ("High Risk Product"). By
 * including Cypress's product in a High Risk Product, the manufacturer
 * of such system or application assumes all risk of such use and in doing
 * so agrees to indemnify Cypress against all liability.
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "key_public.h"

/******************************************************
 *                      Macros
 ******************************************************/

/******************************************************
 *                    Constants
 ******************************************************/

/* RSA privvate key generated by openssl */
/* N, E parts are same with public key */
#define RSA_PRIVATE_N   RSA_PUBLIC_N
#define RAS_PRIVATE_E   RSA_PUBLIC_E
#define RSA_PRIVATE_D   "67903120d5d7a62872ad219e3a4d54cbee9a20d8ceffb78e774ab9a2609bc886802309f55a422307eeac55357b3815ccb38e538f44fb42fd4211ad7a97694e425db401b0f37497e3f622438717ae700ced9d852845916d34d66941827261a31f93e408ff1f173520a9a89b99d792c3fdd10d50af656a26bbee6727841129613c97ee93a63ac008688e4ad207c758a3eb7ac1610c1947b1c434e7147d30489ce8b98761d81019af8941171d9473c64776dc842660adf61c6529b9a29d4c62610c5af26a52b01fff8e4209b0eefffdcc24f89e51d6c622b64e283c63c1a3d0d7daed42d34b56e6268e166e62a735cee08c1ec465877ea6b19ec12bfd26246f06e1"
#define RSA_PRIVATE_P   "f14a31bad65f291f36ce5e2cf7f1981b6457b67e481c374d5075bdaecffe47b22ce47d6b9a3a93447f43823945bf2814fecb92cf23ab7ed75351e142f80df7c504ae0b303bae58361667f7aed479e168b93e3d50d2a154785366e4f9a706804d0cac85c37bb3540762d8dcdaf07ce58bf41c84c948fb37c896beda18ff89e09d"
#define RSA_PRIVATE_Q   "de4d228fc19b4c3eeb5e3c876d04bf6ab2a4693457252a9e8e7bae415fd593c2880412c2a1ad5c6dc69aada9f110a4e75d0cf6847b3c86aaca5f4140e9eea96e18e525c2aa393e6d77094f11010e182ad7e4710e3bd5c815a59e94db0593283cf845f038eefa7083130d5647771fdf6ef3cdb5fa8b8570a5519cb6d7c2890d49"
#define RSA_PRIVATE_DP  "1c1683f578f0f8eb7e48c5a3bc752e3cba108fd8e1720f69fb9cc928e963735b2568afc4efde33b87c8c1243b27fcf1daa8f6e1698d364df91fe6d178ba2ac9e0dae68f5036d872d3cac7ba3a96e4ab4132450a4f0f000d244fb2c5a777c054172e13e6d04205afec51df38fb5010503a6b60f2b1348d334917fc409b6ed88ed"
#define RSA_PRIVATE_DQ  "dcead902f60b884d2b08deac530a19d4462e1fa2f54ba93c232b04745171e5c2b7fb1c4db1f09fdf3434b98b1e574519ec1e1aca73d2259e8b38f89733238bdb2f0062733f495e21d8df366516a0542217a51d3960fb463944fb00c15c9beeac10ab285cdc19a4408e697da9cdd7adeb0c7d0d712cc072bec8092ea7e2dae289"
#define RSA_PRIVATE_QP  "bf31f2b1391639609c12469a037da46f77016c4431488f0950ace1b1f2573ca377deadaaba1e1f3d1311bd5d8d9adccff7c8a1409c79a96f184b778df6d0941c6c1d8eb433cdc81b060d2543be96794a98f2b026e42a975326abd6ffdeed27361235aaf002bac23d31af8a2e3e0b59174bc6a6a90a3991073f5bca33ceaed7c8"

/******************************************************
 *                   Enumerations
 ******************************************************/

/******************************************************
 *                 Type Definitions
 ******************************************************/

/******************************************************
 *                    Structures
 ******************************************************/

/******************************************************
 *                 Global Variables
 ******************************************************/

/******************************************************
 *               Function Declarations
 ******************************************************/

#ifdef __cplusplus
} /* extern "C" */
#endif
