/*
 * Copyright 2018, Cypress Semiconductor Corporation or a subsidiary of 
 * Cypress Semiconductor Corporation. All Rights Reserved.
 * 
 * This software, associated documentation and materials ("Software"),
 * is owned by Cypress Semiconductor Corporation
 * or one of its subsidiaries ("Cypress") and is protected by and subject to
 * worldwide patent protection (United States and foreign),
 * United States copyright laws and international treaty provisions.
 * Therefore, you may use this Software only as provided in the license
 * agreement accompanying the software package from which you
 * obtained this Software ("EULA").
 * If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
 * non-transferable license to copy, modify, and compile the Software
 * source code solely for use in connection with Cypress's
 * integrated circuit products. Any reproduction, modification, translation,
 * compilation, or representation of this Software except as specified
 * above is prohibited without the express written permission of Cypress.
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
 * reserves the right to make changes to the Software without notice. Cypress
 * does not assume any liability arising out of the application or use of the
 * Software or any product or circuit described in the Software. Cypress does
 * not authorize its products for use in any products where a malfunction or
 * failure of the Cypress product may reasonably be expected to result in
 * significant property damage, injury or death ("High Risk Product"). By
 * including Cypress's product in a High Risk Product, the manufacturer
 * of such system or application assumes all risk of such use and in doing
 * so agrees to indemnify Cypress against all liability.
 */

/**
 * @file
 * This provides the content (web pages) which will be served when the
 * Appliance App has been configured and connected to an external Access Point.
 *
 * It does not use a filesystem, all pages are generated by handler functions.
 * These functions simply copy data into the outgoing packet buffer.
 *
 */

#include "web_server.h"
#include "brcmlogos.h"
#include "wwd_wifi.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "wwd_assert.h"
#include "appliance.h"
#include "internal/wwd_sdpcm.h"
#include "wwd_wlioctl.h"

/******************************************************
 *                      Macros
 ******************************************************/

/******************************************************
 *                    Constants
 ******************************************************/
#define SSID_FIELD_NAME            "ssid"
#define SECURITY_FIELD_NAME        "sec"
#define CHANNEL_FIELD_NAME         "chan"
#define BSSID_FIELD_NAME           "bssid"
#define PASSPHRASE_FIELD_NAME      "pwd"
#define PIN_FIELD_NAME             "pin"

/******************************************************
 *                   Enumerations
 ******************************************************/

/******************************************************
 *                 Type Definitions
 ******************************************************/

/******************************************************
 *                    Structures
 ******************************************************/
typedef struct
{
    uint8_t scan_done;
    host_semaphore_type_t result_avail_sema;
    wiced_scan_result_t* result_buff;
} scan_cb_t;

/******************************************************
 *               Static Function Declarations
 ******************************************************/
static int  process_top           ( void* socket, char * params, int params_len );

/******************************************************
 *               Variable Definitions
 ******************************************************/

/**
 * URL Handler List
 */
const url_list_elem_t config_STA_url_list[] = {
                                     { "/",             "text/html",                process_top },
                                     { "/favicon.ico",  "image/vnd.microsoft.icon", process_favicon },
                                     { "/brcmlogo.jpg", "image/jpeg",               process_brcmlogo },
                                     /* Add more pages here */
                                     { NULL, NULL, NULL }
                                   };


/**
 * HTML data for main sensor web page
 */
static const char top_web_page_top[] =
    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN " "http://www.w3.org/TR/html4/strict.dtd\">\n"
    "<html>\n"
    "  <head>\n"
    "    <title>WICED Appliance</title>\n"
    "  </head>\n"
    "  <body style=\"font-family:verdana;\" >\n"
    "    <h2 align=\"center\"><img src=\"brcmlogo.jpg\"/> <span style=\"color:#ff0000\">Broadcom</span> WICED Appliance</h2><hr>\n"
    "<p>Button presses are sent to " PLATFORM " UART.</p>"
    "<form name=\"input\" action=\"/\" method=\"get\"> <table> <tr>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-01\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-02\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-03\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-04\" /></td>\n"
    "</tr>"
    "<td><input type=\"submit\" name=btname value=\"Button-05\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-06\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-07\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-08\" /></td>\n"
    "</tr>"
    "<td><input type=\"submit\" name=btname value=\"Button-09\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-10\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-11\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-12\" /></td>\n"
    "</tr>"
    "<td><input type=\"submit\" name=btname value=\"Button-13\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-14\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-15\" /></td>\n"
    "<td><input type=\"submit\" name=btname value=\"Button-16\" /></td>\n"
    "</tr>"
    "</form>"
    "  </body>\n"
    "</html>\n";


/******************************************************
 *               Function Definitions
 ******************************************************/

/**
 * URL handler for serving web buttons / UART demo
 *
 * Checks if the GET parameters contain a button name, and writes any names found to the UART
 *
 * @param  socket  : a handle for the TCP socket over which the data will be sent
 * @param  params     : a byte array containing any parameters included in the URL
 * @param  params_len : size of the params byte array in bytes
 */
static int process_top( void* socket, char * params, int params_len )
{
    char * found_loc = NULL;
    char  end_found = 0;
    /* Process the GET parameter list to determine if buttons have been pressed */

    /* Cycle through parameter list string until end or newline */
    while ( end_found == 0 )
    {
        /* Check if parameter is "led" */
        if ( 0 == strncmp( params, "btname", 6 ) )
        {
            found_loc = &params[7];
        }

        /* Scan ahead to the next parameter or the end of the parameter list */
        while ( ( *params != '&' ) && ( *params != '\n' ) && ( params_len > 0 ) )
        {
            params++;
            params_len--;
        }

        if  ( *params != '&' )
        {
            end_found = 1;
        }


        if ( found_loc != NULL )
        {
            *params = '\x00';
            WPRINT_APP_INFO( ( "\nDetected button press: %s\n\n", found_loc ) );
        }


        if ( end_found == 0 )
        {
            /* Skip over the "&" which joins parameters if found */
            params++;
        }
    }


    send_web_data( socket, (unsigned char*) top_web_page_top, sizeof( top_web_page_top ) - 1 ); /* minus one to avoid copying terminating null */

    return 0;
}






